import { BRAND, DISCLAIMER_SHORT } from "@/lib/config";

/**
 * The Northlake mark: a rising curve closing on a point.
 *
 * Drawn from scratch for this project. It intentionally shares no shape,
 * colour or letterform with any existing financial institution.
 */
export function BrandMark({ size = 32 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 40 40"
      role="img"
      aria-label={`${BRAND.name} logo`}
      className="shrink-0"
    >
      <rect width="40" height="40" rx="11" fill="var(--color-brand)" />
      <path
        d="M10 27.5C14.5 27.5 17 22 20 17.5C22.5 13.8 25.5 12 29.5 12"
        fill="none"
        stroke="var(--color-brand-contrast)"
        strokeWidth="2.75"
        strokeLinecap="round"
        opacity="0.55"
      />
      <path
        d="M10 27.5C16 27.5 18.5 24 21.5 20.5"
        fill="none"
        stroke="var(--color-brand-contrast)"
        strokeWidth="2.75"
        strokeLinecap="round"
      />
      <circle cx="28.5" cy="13" r="3.6" fill="var(--color-brand-contrast)" />
    </svg>
  );
}

export function Wordmark({ size = 32 }: { size?: number }) {
  return (
    <span className="flex items-center gap-2.5">
      <BrandMark size={size} />
      <span className="flex flex-col leading-none">
        <span className="text-[15px] font-semibold tracking-tight text-ink">
          {BRAND.name}
        </span>
        <span className="mt-1 text-[10.5px] font-medium uppercase tracking-[0.13em] text-muted">
          {BRAND.productName}
        </span>
      </span>
    </span>
  );
}

/**
 * The one persistent marker that the figures are modelled.
 *
 * Deliberately quiet — a chip in the chrome rather than a banner across the
 * page — but always present, on every screen, next to the brand. It is the
 * thing that keeps this a savings model rather than a document that could pass
 * as a real account record. Do not remove it.
 */
export function SimulationChip() {
  return (
    <span
      title="All figures on this page are generated by a compound-interest model."
      className="hidden select-none rounded-full border border-line px-2 py-0.5 text-[10.5px] font-semibold uppercase tracking-[0.1em] text-muted sm:inline-block"
    >
      {DISCLAIMER_SHORT}
    </span>
  );
}
